### ISSUE TITLE
get position by item

### ISSUE THREAD

**Issue by jintoga** [TheCraftKid/FirebaseUI-Android-Addons#1]
Hi! As the title, i need to get the position of an item in spinner so i can select it programmatically. Is there anyway i can achieve such thing?

**Comment by WillieCubed** [comment]
You can get the value of an item by position like any `SpinnerAdapter` by calling the `getItemAtPosition(int position)` method on the `FirebaseSpinnerAdapter`.

**Comment by jintoga** [comment]
no i don't need the item. i need to get it's position.

**Comment by WillieCubed** [comment]
[Here](http://stackoverflow.com/a/4228121/5742625) is a link to relevant information. Since this isn't directly related to the library and more directed to the Android framework, I'm going to close this issue.
